In [2]:
import numpy as np
import pandas as pd

In [ ]:
1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)

In [5]:
answer1

In [ ]:
array1=np.arange(1,11)

In [6]:
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
array1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
2. Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index. (Score:1)


In [5]:
array2=np.arange(1,21)

In [12]:
print(array2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [16]:
print(array2[5:16])

[ 6  7  8  9 10 11 12 13 14 15 16]


In [ ]:
3. How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above (Score 1)

In [6]:
print(np.mean(array2))

10.5


In [7]:
print(np.median(array2))

10.5


In [8]:
print(np.std(array2))

5.766281297335398


In [ ]:
4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)

In [21]:
x=np.array(range(12)).reshape(3,4)
y=np.array([1,2,3,4])

In [25]:
print(x-y)

[[-1 -1 -1 -1]
 [ 3  3  3  3]
 [ 7  7  7  7]]


In [28]:
data={"name":("arun","babu","chandu","devan","elsa","farooq","guru","hafiz","ijaz","jess"),
"age":(31,20,46,37,28,25,34,45,25,38),
"gender":("m","f","m","m","f","m","m","f","m","f")}

In [29]:
dataframe_1=pd.DataFrame(data)

In [30]:
print(dataframe_1)

     name  age gender
0    arun   31      m
1    babu   20      f
2  chandu   46      m
3   devan   37      m
4    elsa   28      f
5  farooq   25      m
6    guru   34      m
7   hafiz   45      f
8    ijaz   25      m
9    jess   38      f


In [32]:
value=("manager","analyst","engineer","Sales","clerk","supervisor","incharge","foreman","helper","accountant")

In [33]:
dataframe_1["occupation"]=value

In [35]:
print(dataframe_1)

     name  age gender  occupation
0    arun   31      m     manager
1    babu   20      f     analyst
2  chandu   46      m    engineer
3   devan   37      m       Sales
4    elsa   28      f       clerk
5  farooq   25      m  supervisor
6    guru   34      m    incharge
7   hafiz   45      f     foreman
8    ijaz   25      m      helper
9    jess   38      f  accountant


In [ ]:
2) Select the rows of the dataframe where the age is greater than or equal to 30.
(Score: 1)

In [37]:
age_30=dataframe_1["age"]>=30

In [40]:
print(dataframe_1[age_30])

     name  age gender  occupation
0    arun   31      m     manager
2  chandu   46      m    engineer
3   devan   37      m       Sales
6    guru   34      m    incharge
7   hafiz   45      f     foreman
9    jess   38      f  accountant


In [ ]:
3) Convert this dataframe to a CSV file and read that CSV file, and finally display
the contents. (Score: 1)

In [42]:

dataframe_1.to_csv("data.csv", index=False)

new_dataframe = pd.read_csv("data.csv")


print(new_dataframe)

     name  age gender  occupation
0    arun   31      m     manager
1    babu   20      f     analyst
2  chandu   46      m    engineer
3   devan   37      m       Sales
4    elsa   28      f       clerk
5  farooq   25      m  supervisor
6    guru   34      m    incharge
7   hafiz   45      f     foreman
8    ijaz   25      m      helper
9    jess   38      f  accountant
